apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis-sentinel-client.fullname" . }}-redis
  labels:
    {{- include "redis-sentinel-client.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redis.password | b64enc }}
